[project]
name = "multifractal-voicepathology"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "nspfile>=0.2.0",
    "pandas>=2.3.3",
    "scipy>=1.17.0",
]
